// Generated by gencpp from file yolo_example/DetectedObject.msg
// DO NOT EDIT!


#ifndef YOLO_EXAMPLE_MESSAGE_DETECTEDOBJECT_H
#define YOLO_EXAMPLE_MESSAGE_DETECTEDOBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <yolo_example/BoundingBox.h>

namespace yolo_example
{
template <class ContainerAllocator>
struct DetectedObject_
{
  typedef DetectedObject_<ContainerAllocator> Type;

  DetectedObject_()
    : label()
    , confidence(0.0)
    , box()  {
    }
  DetectedObject_(const ContainerAllocator& _alloc)
    : label(_alloc)
    , confidence(0.0)
    , box(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _label_type;
  _label_type label;

   typedef double _confidence_type;
  _confidence_type confidence;

   typedef  ::yolo_example::BoundingBox_<ContainerAllocator>  _box_type;
  _box_type box;





  typedef boost::shared_ptr< ::yolo_example::DetectedObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo_example::DetectedObject_<ContainerAllocator> const> ConstPtr;

}; // struct DetectedObject_

typedef ::yolo_example::DetectedObject_<std::allocator<void> > DetectedObject;

typedef boost::shared_ptr< ::yolo_example::DetectedObject > DetectedObjectPtr;
typedef boost::shared_ptr< ::yolo_example::DetectedObject const> DetectedObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo_example::DetectedObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo_example::DetectedObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolo_example::DetectedObject_<ContainerAllocator1> & lhs, const ::yolo_example::DetectedObject_<ContainerAllocator2> & rhs)
{
  return lhs.label == rhs.label &&
    lhs.confidence == rhs.confidence &&
    lhs.box == rhs.box;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolo_example::DetectedObject_<ContainerAllocator1> & lhs, const ::yolo_example::DetectedObject_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolo_example

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolo_example::DetectedObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo_example::DetectedObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_example::DetectedObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_example::DetectedObject_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_example::DetectedObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_example::DetectedObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo_example::DetectedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edf2e0356664286b429d6f21ae05e759";
  }

  static const char* value(const ::yolo_example::DetectedObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xedf2e0356664286bULL;
  static const uint64_t static_value2 = 0x429d6f21ae05e759ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo_example::DetectedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo_example/DetectedObject";
  }

  static const char* value(const ::yolo_example::DetectedObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo_example::DetectedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string label\n"
"float64 confidence\n"
"BoundingBox box\n"
"================================================================================\n"
"MSG: yolo_example/BoundingBox\n"
"float64 x1\n"
"float64 y1\n"
"float64 x2\n"
"float64 y2\n"
;
  }

  static const char* value(const ::yolo_example::DetectedObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo_example::DetectedObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
      stream.next(m.confidence);
      stream.next(m.box);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectedObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo_example::DetectedObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolo_example::DetectedObject_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.label);
    s << indent << "confidence: ";
    Printer<double>::stream(s, indent + "  ", v.confidence);
    s << indent << "box: ";
    s << std::endl;
    Printer< ::yolo_example::BoundingBox_<ContainerAllocator> >::stream(s, indent + "  ", v.box);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_EXAMPLE_MESSAGE_DETECTEDOBJECT_H
